version: '3.4'

services:

  envoyserver:
    image: steeltoeoss/eureka-server
    networks:
      - mynetwork
    ports:
      - 8761:8761

  eurekadiscoverexample:
    image: eurekahelloworld/eurekadiscoverexample:1.0
    build:
      context: .
      dockerfile: EurekaDiscoverExample/Dockerfile
    networks:
      - mynetwork
    ports:
      - 5101:80
    depends_on:
      - envoyserver

  eurekaregisterexample:
    image: eurekahelloworld/eurekaregisterexample:1.0
    build:
      context: .
      dockerfile: EurekaRegisterExample/Dockerfile
    networks:
      - mynetwork
    depends_on:
      - envoyserver

 
networks:
  mynetwork: 
    driver: bridge